repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: end-of-file-fixer
        exclude: .*\.txt
    rev: v5.0.0

  - repo: https://github.com/psf/black
    hooks:
      - id: black
    rev: 24.10.0

  - repo: https://github.com/LilSpazJoekp/docstrfmt
    hooks:
      - id: docstrfmt
    rev: v1.9.0

  - repo: https://github.com/pycqa/flake8
    hooks:
      - id: flake8
    rev: 7.1.1

  - repo: https://github.com/ikamensh/flynt/
    hooks:
      - id: flynt
        args:
          - '-ll'
          - '1000'
    rev: '1.0.1'

  - repo: https://github.com/pycqa/isort
    hooks:
      - id: isort
    rev: 5.13.2

  - repo: https://github.com/pycqa/pydocstyle
    hooks:
      - id: pydocstyle
        files: prawcore/.*
    rev: 6.3.0
