[tool.black]
extend_exclude = '/(\.venv.*)/'
line-length = 88

[tool.isort]
profile = 'black'
skip_glob = '.venv*'

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning"
testpaths = "tests"
